### ISSUE TITLE
Calcul du Nombre de services numériques

### ISSUE THREAD

**Issue by LudovicLeman** [lowdit/frago#10]
Le calcul du nombre de services numériques semble se baser sur les fichiers CSV présent dans mon cas, j'ai 5 projets mais un nombre de services numériques égale à 8

**Comment by bertrandkeller** [comment]
Identique.

Corrigé mais non poussé. J'ai bossé sur les calculs
Me demande d'ailleurs si une médiane serait pas plus pertinente qu'une moyenne.

Le calcul semble aussi lourd. En temps de calcul. Je dois revoir cela. Il y aura encore d'autres modifications.

**Comment by bertrandkeller** [comment]
Le code a été mis à jour en v1.12.2

À tester.
