### ISSUE TITLE
Problème lors du déplacement du répertoire themes

### ISSUE THREAD

**Issue by firewalkwizme** [lowdit/frago#15]
Bonjour,

Afin de n'avoir qu'un unique répertoire "thèmes" commun à l'ensemble de mes sites, j'ai déplacé mon répertoire "themes" dans le répertoire "sites" et lancé la commande suivante. J'ai une erreur que je ne comprends pas :-/

```
PS C:\Users\ygoupil\Hugo\sites\Test> C:\Users\ygoupil\Hugo\bin\hugo --themesDir ../sites/themes/frago/
Error: module "frago" not found; either add it as a Hugo Module or store it in "C:\\Users\\ygoupil\\Hugo\\sites\\sites\\themes\\frago".: module does not exist
```

**Comment by bertrandkeller** [comment]
Hello,

_Je suis en Suisse avec mon fils. Encore dans le train_

Il dit : je ne trouve pas le thème Frago qui est appelé dans le config.toml.
Donc que le chemin indiqué n'est pas le bon.

Je vois des slash dans `--themesDir ../sites/themes/frago/` est-ce que ça marche ou `--themesDir ..\sites\themes\frago` est mieux sous windows.

Tu dois appeler `themes` qui contient `frago`, tu ne dois donc pas appeler `frago` mais seulement `themes`. 
Car tu peux appeler plusieurs thèmes (ou sous-thèmes) dans le même Hugo, c'est pas un souci.

Donc plutôt `--themesDir ..\sites\themes` ou `--themesDir ..\themes` (si `themes` à la racine de tes dépôts). Si c'est bien le bon chemin et les bons slash.

Si c'est indications sont clairs, tu devrais trouver le chemin qui mène à `themes`.

**Comment by firewalkwizme** [comment]
J'ai mis le chemin complet en absolu (C:\\Users\\.......) et ça marche !
