### ISSUE TITLE
Exemples

### ISSUE THREAD

**Issue by jpboignard** [lowdit/frago#5]
Bonjour, 
Est-il possible de compléter la documentation et exampleSite avec une arborescence plus complète de fichiers qui rende compte des formats source acceptés et de l'implémentation en cours des différents référentiels ?

Merci d'avance

**Comment by bertrandkeller** [comment]
Même si la structure est assez ancienne. 

Pas besoin de déclarer les fichiers de contenu, il me semble.

**Comment by bertrandkeller** [comment]
Hello,

Est-ce que ça c'est mieux comme exampleSite ?
https://github.com/lowdit/frago/tree/master/exampleSite/content
