### ISSUE TITLE
Problème avec les espaces dans les noms d'audits et les URL's générées

### ISSUE THREAD

**Issue by firewalkwizme** [lowdit/frago#7]
Bonjour Bertrand,

J'ai créé un répertoire projet nommé "Passeport de prevention"
Lorsque je tente de cliquer sur le rapport, j'ai une erreur 404.

En effet, l'URL de mon rapport est /audits/Passeport%20de%20prevention/accessibility.html

Mais le build génère un répertoire nommé passeport-de-prevention
L'url /audits/passeport-de-prevention/accessibility.html fonctionne bien du coup.

Est-ce que l'adresse du lien peut être formatée avec le bon nom stp ?

**Comment by firewalkwizme** [comment]
_"Le nom de répertoire est considéré comme un slug a priori."_

OK, il suffit de le savoir.
Peut-être le mettre clairement dans [la doc](https://lowdit.github.io/frago/docs/renseigner/audit-renseigner/) ou alors ça m'a échappé.
=> Ajouter un warning

**Comment by bertrandkeller** [comment]
C'est corrigé. 

Les urls sont formées à partir du nom du projet. Du nom de répertoire.
Maintenant, ça ne casse plus les urls.

Ce pose question si on devait s'en servir pour la construction de fichiers généraux. Voir :
https://github.com/lowdit/frago/issues/6

Par exemple pour la notion de priorisation des services numériques.
