### ISSUE TITLE
La suppression du fichier RGESN/GreenIT provoque un bug

### ISSUE THREAD

**Issue by LudovicLeman** [lowdit/frago#9]
Si je n'ajoute pas au minimum dans un projet un fichier RGESN le site plante et m'indique les erreurs suivante : 

![image](https://user-images.githubusercontent.com/124707522/217303187-6e03f948-e28f-4d4e-9386-89e641078b25.png)

**Comment by bertrandkeller** [comment]
Oui.

Bug sur la dernière version. Corrigé depuis mais code pas poussé.

Tests à faire selon différentes présences de contenu.

**Comment by bertrandkeller** [comment]
Le code a été mis à jour en v1.12.2

À tester.

**Comment by bertrandkeller** [comment]
Performance créait un bug du même type c'est corrigé
